# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
name: umi-next

trigger:
  - master

jobs:
  - job: windows_test
    timeoutInMinutes: 30
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - checkout: self
        clean: all
        fetchDepth: 1
      - script: yarn install
        displayName: install
      - script: yarn build
        displayName: build
      - script: yarn test -- --forceExit --detectOpenHandles --runInBand
        env:
          PROGRESS: none
          CI: true
        displayName: test
