name: Node CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [8.x, 10.x, 12.x]
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - run: yarn --ignore-engines
      - run: yarn build
      - run: yarn test --forceExit -t createMiddleware
        env:
          CI: true
          DEBUG: umi:preset-build-in:mock*
          HEADLESS: false
          PROGRESS: none
          NODE_ENV: test
          NODE_OPTIONS: --max_old_space_size=4096

